trigger: none
pr: none

resources:
    pipelines:
        - pipeline: DurableJSCI
          project: "Azure Functions"
          source: azure-functions-durable-js
          branch: main

jobs:
    - job: Release
      pool:
          name: "1ES-Hosted-AzFunc"
          demands:
              - ImageOverride -equals MMSUbuntu20.04TLS
      steps:
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
                versionSpec: 14.x
          - download: DurableJSCI
          - script: mv *.tgz package.tgz
            displayName: "Rename tgz file" # because the publish command below requires an exact path
            workingDirectory: "$(Pipeline.Workspace)/DurableJSCI/drop"
          - script: echo -e "registry=https://registry.npmjs.org/ >" .npmrc
            workingDirectory: "$(Pipeline.Workspace)/DurableJSCI/drop"
          - script: touch test
            workingDirectory: "$(Pipeline.Workspace)/DurableJSCI/drop"
          - script: touch test2
            workingDirectory: "$(Pipeline.Workspace)/DurableJSCI/drop"
          - script: "ls -a"
            workingDirectory: "$(Pipeline.Workspace)/DurableJSCI/drop"
          - task: npmAuthenticate@0
            inputs:
              workingFile: $(Pipeline.Workspace)/DurableJSCI/drop/.npmrc
              customEndpoint: "NPM Durable Functions JS Publish"
          - script: npm publish package.tgz
            workingDirectory: "$(Pipeline.Workspace)/DurableJSCI/drop"