trigger:
    branches:
        include:
            - v2.x
            - v3.x

schedules:
# Build nightly to catch any new CVEs and report SDL often.
# We are also required to generated CodeQL reports weekly, so this
# helps us meet that.
- cron: "0 0 1/7 * *"
  displayName: Weekly sync
  branches:
    include:
    - v3.x
  always: true

resources:
    repositories:
        - repository: eng
          type: git
          name: engineering
          ref: refs/tags/release

variables:
    - template: ci/variables/cfs.yml@eng

extends:
    template: ci/code-mirror.yml@eng
